apiVersion: v1
kind: ConfigMap
metadata:
  name: smartops-config
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.ASPNETCORE_ENVIRONMENT | quote }}
  Redis__Configuration: {{ printf "%s:%v" .Values.config.redisHost .Values.config.redisPort | quote }}

  # Do NOT put SA password in ConfigMap. Use env + secret for password.
  # Keep the parts of connection string that aren't secret:
  ConnectionStrings__DefaultConnection: {{ printf "Server=%s;Database=%s;User Id=%s;TrustServerCertificate=%v;" .Values.config.sqlHost .Values.config.sqlDb .Values.config.sqlUser .Values.config.trustServerCertificate | quote }}