{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-redis
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: smartops-redis
  template:
    metadata:
      labels:
        app: smartops-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          ports:
            - containerPort: {{ .Values.redis.port }}
{{- end }}