{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: smartops-redis
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  selector:
    app: smartops-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
{{- end }}