apiVersion: v1
kind: Secret
metadata:
  name: smartops-secrets
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.secrets.saPassword | quote }}
  JWT_KEY: {{ .Values.secrets.jwtKey | quote }}